name: Run ESLint
on: [push]
jobs:
  Run-ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install dev dependencies
        run: npm install --only=dev
      - name: These are all the files
        run: |
          ls ${{ github.workspace }}
      - name: Run ESLint
        run: npm run lint
      - run: echo "🍏 This job's status is ${{ job.status }}."
